### PR TITLE
add Makefile

### PR DESCRIPTION
**Pull request by vanym**
Replace build.sh with a canonical Makefile. Update README.md and add .sh example.

### CODE REVIEW

**Comment by ryancdotorg** [comment]
I don't feel entirely comfortable encouraging people to install this as root.

Can you please change `PREFIX?=/usr/local` to
```
ifeq ($(origin SUDO_USER)$(shell id -u),environment0)
    PREFIX?=/usr/local
else
    PREFIX?=$(HOME)/.local
endif
```
and update the README and examples accordingly?

If you update your branch it should update the pull request.

**Comment by vanym** [comment]
Okay I'll add rootless install support

**Comment by ryancdotorg** [comment]
Please also feel free to add yourself under Authors!

**Comment by vanym** [comment]
> `ifeq ($(origin SUDO_USER)$(shell id -u),environment0)`

In this case we must have sudo to install system-wide (or use hack `SUDO_USER=1 make install`). When building in container it's usually without sudo.

Maybe check only for root?

**Comment by ryancdotorg** [comment]
My thinking is to make the behavior consistent. 

Install system-wide if installed with `sudo` to root.

Install to home directory if run without `sudo`, or as a user other than root.

If someone wants to install it system-wide as root without `sudo`, they could still do that with `PREFIX=/usr/local make install` or `make PREFIX=/usr/local install`.

If anything, it might be better to remove the uid 0 check since it's not super clear what the user wants in that case, and it might fail due to permissions.

**Comment by vanym** [comment]
Oh, it's just canonical for `make install` to install to prefix `/usr/local` by default. CMake [do that](https://cmake.org/cmake/help/v3.28/variable/CMAKE_INSTALL_PREFIX.html#cmake-install-prefix), automake [do that](https://www.gnu.org/software/automake/manual/html_node/Standard-Directory-Variables.html), meson [do that](https://mesonbuild.com/Builtin-options.html)

**Comment by ryancdotorg** [comment]
Okay.

**Comment by ryancdotorg** [comment]
Merged, thanks! I added some further improvements to the Makefile. I know how to use make reasonably well, sometimes I'm just lazy. 😅

**Pull request merged**
